"""红队/SRC 出网硬约束：proxychains 套住 connect()，并拦截故意直连。"""
from __future__ import annotations

import os
import re
import shlex
import tempfile
from pathlib import Path
from urllib.parse import unquote, urlparse

from ..config import settings

_PROXYCHAINS = "/usr/bin/proxychains4"

# 原始套接字 / 不走 libc connect 的扫描器：proxychains 拦不住。
_RAW_SOCKET_RE = re.compile(
    r"(?:^|[\s;&|`(])(?:/usr/(?:s?bin)/)?(?:nmap|masscan|hping3?|nping|zmap|naabu|rustscan)\b",
    re.I,
)
_BYPASS_RE = re.compile(
    r"--noproxy\b"
    r"|CURL_NOPROXY\b"
    r"|(?:^|[\s;])(?:NO_PROXY|no_proxy|ALL_PROXY|all_proxy|HTTP_PROXY|HTTPS_PROXY|http_proxy|https_proxy)=\*",
    re.I,
)
_UNSET_PROXY_RE = re.compile(
    r"\bunset\s+(?:[A-Za-z0-9_]*PROXY[A-Za-z0-9_]*\s*)+"
    r"|\benv\s+-u\s+\w*PROXY"
    r"|LD_PRELOAD=",
    re.I,
)
_UNHOOK_RE = re.compile(
    r"\b(?:unset|env\s+-u)\s+[^\n;]*LD_PRELOAD",
    re.I,
)


def proxy_bypass_reason(command: str) -> str | None:
    """命令若会绕过出口代理，返回拦截原因。"""
    blob = command or ""
    if not blob.strip():
        return None
    if _RAW_SOCKET_RE.search(blob):
        return (
            "红队/SRC 必须走出口代理。nmap/masscan/hping 用原始套接字，会漏真实 IP。"
            "改用 curl / http_request / ffuf（平台会强制套 proxychains）。"
        )
    if _BYPASS_RE.search(blob) or _UNSET_PROXY_RE.search(blob) or _UNHOOK_RE.search(blob):
        return (
            "红队/SRC 禁止 --noproxy、清空代理环境变量或卸掉 LD_PRELOAD。"
            "出网由平台强制走存活代理，不要对照实验直连。"
        )
    return None


def split_proxy_url(url: str) -> tuple[str, str, int, str, str] | None:
    raw = (url or "").strip()
    if not raw:
        return None
    u = urlparse(raw)
    host = (u.hostname or "").strip()
    if not host:
        return None
    scheme = (u.scheme or "http").lower()
    if scheme in ("socks5h", "socks5"):
        kind = "socks5"
        port = int(u.port or 1080)
    elif scheme.startswith("socks4"):
        kind = "socks4"
        port = int(u.port or 1080)
    else:
        kind = "http"
        port = int(u.port or 8080)
    user = unquote(u.username) if u.username else ""
    passwd = unquote(u.password) if u.password else ""
    return kind, host, port, user, passwd


def _conf_line(url: str) -> str | None:
    parsed = split_proxy_url(url)
    if not parsed:
        return None
    kind, host, port, user, passwd = parsed
    extra = f" {user} {passwd}" if user else ""
    return f"{kind} {host} {port}{extra}"


def write_proxychains_conf(proxy_urls: str | list[str]) -> Path:
    raw = proxy_urls if isinstance(proxy_urls, (list, tuple)) else [proxy_urls]
    lines: list[str] = []
    seen: set[str] = set()
    for u in raw:
        line = _conf_line(str(u or ""))
        if not line or line in seen:
            continue
        seen.add(line)
        lines.append(line)
    if not lines:
        raise ValueError("无效代理 URL")
    # round_robin + chain_len=1：每次 connect 只用一跳；死节点跳过，换列表里下一个。
    # 禁止 strict_chain 钉死单个 SOCKS，也禁止 dynamic_chain 把池子串成多跳。
    text = (
        "# generated by atkbrain; do not edit\n"
        "quiet_mode\n"
        "proxy_dns\n"
        "round_robin_chain\n"
        "chain_len = 1\n"
        "tcp_read_time_out 15000\n"
        "tcp_connect_time_out 3000\n"
        "localnet 127.0.0.0/255.0.0.0\n"
        "[ProxyList]\n"
        + "".join(f"{ln}\n" for ln in lines)
    )
    root = Path(settings.data_dir) / "proxy-run"
    root.mkdir(parents=True, exist_ok=True)
    fd, name = tempfile.mkstemp(prefix="pc-", suffix=".conf", dir=str(root))
    os.close(fd)
    path = Path(name)
    path.write_text(text, encoding="utf-8")
    try:
        os.chmod(path, 0o600)
    except OSError:
        pass
    return path


def wrap_proxychains(command: str, proxy_urls: str | list[str]) -> str:
    """用 proxychains4 套住整条 shell，子进程 connect() 都走代理。"""
    cmd = (command or "").strip()
    if not cmd:
        return cmd
    if re.match(r"^(?:/usr/bin/)?proxychains4?\b", cmd):
        return cmd
    if not os.path.isfile(_PROXYCHAINS):
        raise FileNotFoundError(_PROXYCHAINS)
    conf = write_proxychains_conf(proxy_urls)
    return (
        f"{_PROXYCHAINS} -q -f {shlex.quote(str(conf))} "
        f"/bin/bash -lc {shlex.quote(cmd)}"
    )


def proxy_url_from_env(env: dict[str, str] | None) -> str | None:
    if not env:
        return None
    for k in ("ALL_PROXY", "all_proxy", "HTTPS_PROXY", "https_proxy", "HTTP_PROXY", "http_proxy"):
        v = str(env.get(k) or "").strip()
        if v:
            if v.lower().startswith("socks5h://"):
                return "socks5://" + v.split("://", 1)[1]
            return v
    return None
